"""empty message

Revision ID: c8250cbb0a37
Revises: 645d3091547b
Create Date: 2019-12-28 18:48:17.493603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8250cbb0a37'
down_revision = '645d3091547b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('program_order_index', 'sections', ['program_id', 'order_index'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('program_order_index', 'sections', type_='unique')
    # ### end Alembic commands ###
