"""add constraints to programs

Revision ID: e80734511bf8
Revises: 2ac5e0a64bf7
Create Date: 2019-12-27 20:25:31.203479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80734511bf8'
down_revision = '2ac5e0a64bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('programs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('programs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'programs', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programs', type_='unique')
    op.alter_column('programs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('programs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
